export interface VenezuelaState {
  id: number;
  name: string;
}

export const VENEZUELA_STATES: VenezuelaState[] = [
  { id: 1, name: "Amazonas" },
  { id: 2, name: "Anzoátegui" },
  { id: 3, name: "Apure" },
  { id: 4, name: "Aragua" },
  { id: 5, name: "Barinas" },
  { id: 6, name: "Bolívar" },
  { id: 7, name: "Carabobo" },
  { id: 8, name: "Cojedes" },
  { id: 9, name: "Delta Amacuro" },
  { id: 10, name: "Distrito Capital" },
  { id: 11, name: "Falcón" },
  { id: 12, name: "Guárico" },
  { id: 13, name: "Lara" },
  { id: 14, name: "Mérida" },
  { id: 15, name: "Miranda" },
  { id: 16, name: "Monagas" },
  { id: 17, name: "Nueva Esparta" },
  { id: 18, name: "Portuguesa" },
  { id: 19, name: "Sucre" },
  { id: 20, name: "Táchira" },
  { id: 21, name: "Trujillo" },
  { id: 22, name: "La Guaira" },
  { id: 23, name: "Yaracuy" },
  { id: 24, name: "Zulia" },
  { id: 25, name: "Dependencias Federales" },
];

export const VENEZUELA_CITIES_BY_STATE: Record<number, string[]> = {
  1: ["Puerto Ayacucho"],
  2: ["Barcelona", "Puerto La Cruz", "El Tigre", "Anaco", "Lechería"],
  3: ["San Fernando de Apure", "Guasdualito"],
  4: ["Maracay", "Turmero", "La Victoria", "Cagua", "El Limón"],
  5: ["Barinas", "Socopó", "Barinitas"],
  6: ["Ciudad Bolívar", "Ciudad Guayana", "Puerto Ordaz", "San Félix", "Upata"],
  7: ["Valencia", "Puerto Cabello", "Guacara", "Naguanagua", "San Diego"],
  8: ["San Carlos", "Tinaquillo"],
  9: ["Tucupita"],
  10: ["Caracas"],
  11: ["Coro", "Punto Fijo", "Punta Cardón"],
  12: ["San Juan de los Morros", "Valle de la Pascua", "Calabozo", "Zaraza"],
  13: ["Barquisimeto", "Cabudare", "Carora", "El Tocuyo", "Quíbor"],
  14: ["Mérida", "El Vigía", "Ejido", "Tovar"],
  15: ["Los Teques", "Santa Teresa del Tuy", "Guarenas", "Guatire", "Petare", "Charallave", "Cúa", "Higuerote"],
  16: ["Maturín", "Punta de Mata", "Caripe"],
  17: ["La Asunción", "Porlamar", "Pampatar", "Juan Griego"],
  18: ["Guanare", "Acarigua", "Araure", "Turén"],
  19: ["Cumaná", "Carúpano", "Güiria", "Cumanacoa"],
  20: ["San Cristóbal", "Táriba", "San Antonio del Táchira", "Rubio", "La Grita"],
  21: ["Trujillo", "Valera", "Boconó", "Carache"],
  22: ["La Guaira", "Catia La Mar", "Maiquetía", "Macuto", "Caraballeda"],
  23: ["San Felipe", "Yaritagua", "Nirgua", "Chivacoa"],
  24: ["Maracaibo", "Cabimas", "Ciudad Ojeda", "Machiques", "La Concepción", "Santa Rita"],
  25: ["Los Roques"],
};
